"""Generate a human-readable report from prediction results."""

import csv
import os
from datetime import datetime

OUTPUTS_DIR = os.path.join("outputs")
HIGH_RISK_THRESHOLD = 0.7


def generate_report(patient_id, findings, output_path=None):
    """Write a text summary and a CSV of per-nodule findings."""
    os.makedirs(OUTPUTS_DIR, exist_ok=True)
    output_path = output_path or os.path.join(OUTPUTS_DIR, f"report_{patient_id}.txt")
    csv_path = os.path.join(OUTPUTS_DIR, "predictions.csv")

    high_risk = [f for f in findings if f["malignancy_probability"] >= HIGH_RISK_THRESHOLD]

    with open(output_path, "w") as f:
        f.write(f"Lung nodule screening report\n")
        f.write(f"Patient ID: {patient_id}\n")
        f.write(f"Generated: {datetime.now().isoformat()}\n")
        f.write("=" * 45 + "\n")
        f.write(f"Total candidate nodules found: {len(findings)}\n")
        f.write(f"High-risk findings (p >= {HIGH_RISK_THRESHOLD}): {len(high_risk)}\n\n")

        for i, finding in enumerate(findings, 1):
            f.write(
                f"  Nodule {i}: location=({finding['y']}, {finding['x']}), "
                f"radius={finding['radius']:.1f}px, "
                f"malignancy_probability={finding['malignancy_probability']:.3f}\n"
            )

        f.write("\nNote: This report is generated by an automated research tool and\n")
        f.write("is not a substitute for review by a qualified radiologist.\n")

    write_predictions_csv(patient_id, findings, csv_path)
    print(f"Report saved to {output_path}")
    return output_path


def write_predictions_csv(patient_id, findings, csv_path):
    file_exists = os.path.exists(csv_path)
    with open(csv_path, "a", newline="") as f:
        writer = csv.writer(f)
        if not file_exists:
            writer.writerow(["patient_id", "y", "x", "radius", "malignancy_probability"])
        for finding in findings:
            writer.writerow([
                patient_id, finding["y"], finding["x"],
                finding["radius"], finding["malignancy_probability"],
            ])